import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// import "./globals.css";

const inter = Roboto({ subsets: ["latin"], weight: ['400', '700'], });

export const metadata: Metadata = {
  title: "Rikkei Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
    </html>
  );
}
